import "./globals.css";
import { Inter } from "next/font/google";
import NavbarSimple from "@/components/navbar/index";
import Footer from "@/components/footer/index";
import Navbar from "@/components/navbar/navbar-second";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b border-1 shadow-sm mb-5 md:mb-0">
          <NavbarSimple />
        </div>
        <div className="border-b border-1 shadow-sm mb-5 md:mb-0">
          <Navbar />
        </div>

        <div>{children}</div>

        <Footer />
      </body>
    </html>
  );
}
